[groups.native_tls]
members = ["hyper-tls", "native-tls-crate", "tokio-native-tls"]

[groups.rustls]
members = ["hyper-rustls", "rustls", "tokio-rustls", "openssl-sys"]

[groups.openssl]
members = ["openssl-sys", "native-tls"]

[groups.boring]
members = ["boring-sys2", "boring2"]

# [[rules]]
# name = "TLS Capability"
# type = "exactly_one_of"
# targets = ["native_tls", "rustls"]
# fix_hint = "Exactly one of native TLS or rustls must be used as TLS provider."

[[rules]]
name = "SSL Provider"
type = "exactly_one_of"
targets = ["openssl", "boring"]
severity = "fatal"
fix_hint = "Exactly one of SSL providers must be used. Remove either openssl or boring."
