[labels.native_tls]
members = ["hyper-tls", "native-tls-crate", "tokio-native-tls"]
categories = ["tls"]

[labels.rustls]
members = ["hyper-rustls", "rustls", "tokio-rustls", "openssl-sys"]
categories = ["tls"]

[labels.openssl]
members = ["openssl-sys", "native-tls"]
categories = ["ssl-provider"]

[labels.boring]
members = ["boring-sys2", "boring2"]
categories = ["ssl-provider"]

[[rules]]
name = "TLS Capability"
type = "exactly_one_of"
targets = ["tls"]
fix_hint = "Exactly one of native TLS or rustls must be used as TLS provider."

[[rules]]
name = "SSL Provider"
type = "exactly_one_of"
targets = ["ssl-provider"]
fix_hint = "Strictly one of OpenSSL or BoringSSL can only be used."
